# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_contact_plus', '0005_extrafield_css_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactplus',
            name='template',
            field=models.CharField(choices=[(b'cmsplugin_contact_plus/contact.html', b'Contact Form'), (b'cmsplugin_contact_plus/contact_newsletter.html', b'Newsletter Form')], default=b'cmsplugin_contact_plus/contact.html', max_length=255),
        ),
    ]
